"""initial schema

Revision ID: a0737ec49a78
Revises: 
Create Date: 2026-09-06 06:26:08.458366
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'a0737ec49a78'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('competitors', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_profiles'))
    )
    op.create_index(op.f('ix_profiles_domain'), 'profiles', ['domain'], unique=True)
    op.create_table('pipeline_runs',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('profile_uuid', sa.Uuid(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'partial', 'failed', name='run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_retrieval_count', sa.Integer(), nullable=False),
    sa.Column('successful_retrieval_count', sa.Integer(), nullable=False),
    sa.Column('normalized_record_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('degradation_reason', sa.Enum('no_plan_produced', 'all_retrievals_failed', 'insufficient_retrievals', 'normalization_empty', 'analysis_unavailable', 'upstream_circuit_open', name='degradation_reason'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name=op.f('ck_pipeline_runs_completed_after_started')),
    sa.CheckConstraint('total_tokens >= 0', name=op.f('ck_pipeline_runs_total_tokens_non_negative')),
    sa.ForeignKeyConstraint(['profile_uuid'], ['profiles.uuid'], name=op.f('fk_pipeline_runs_profile_uuid_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_pipeline_runs'))
    )
    op.create_index('ix_pipeline_runs_correlation_id', 'pipeline_runs', ['correlation_id'], unique=False)
    op.create_index('ix_pipeline_runs_profile_started', 'pipeline_runs', ['profile_uuid', 'started_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_profile_uuid'), 'pipeline_runs', ['profile_uuid'], unique=False)
    op.create_table('discovered_queries',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('profile_uuid', sa.Uuid(), nullable=False),
    sa.Column('run_uuid', sa.Uuid(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('estimated_search_volume', sa.Integer(), nullable=False),
    sa.Column('competitive_difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('visibility_status', sa.Enum('visible', 'not_visible', 'unknown', name='visibility_status'), nullable=False),
    sa.Column('visibility_position', sa.Integer(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(visibility_status = 'visible') = (visibility_position IS NOT NULL)", name=op.f('ck_discovered_queries_position_present_iff_visible')),
    sa.CheckConstraint('competitive_difficulty >= 0 AND competitive_difficulty <= 100', name=op.f('ck_discovered_queries_competitive_difficulty_in_range')),
    sa.CheckConstraint('estimated_search_volume >= 0', name=op.f('ck_discovered_queries_search_volume_non_negative')),
    sa.CheckConstraint('opportunity_score >= 0 AND opportunity_score <= 1', name=op.f('ck_discovered_queries_opportunity_score_in_range')),
    sa.CheckConstraint('visibility_position IS NULL OR visibility_position >= 1', name=op.f('ck_discovered_queries_visibility_position_positive')),
    sa.ForeignKeyConstraint(['profile_uuid'], ['profiles.uuid'], name=op.f('fk_discovered_queries_profile_uuid_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_uuid'], ['pipeline_runs.uuid'], name=op.f('fk_discovered_queries_run_uuid_pipeline_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_discovered_queries'))
    )
    op.create_index('ix_discovered_queries_profile_discovered', 'discovered_queries', ['profile_uuid', 'discovered_at'], unique=False)
    op.create_index('ix_discovered_queries_run_opportunity', 'discovered_queries', ['run_uuid', 'opportunity_score'], unique=False, postgresql_ops={'opportunity_score': 'DESC'})
    op.create_index('ix_discovered_queries_run_status', 'discovered_queries', ['run_uuid', 'visibility_status'], unique=False)
    op.create_table('insights',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('run_uuid', sa.Uuid(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('supporting_query_uuids', postgresql.ARRAY(sa.Uuid()), server_default='{}', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 1', name=op.f('ck_insights_relevance_score_in_range')),
    sa.ForeignKeyConstraint(['run_uuid'], ['pipeline_runs.uuid'], name=op.f('fk_insights_run_uuid_pipeline_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_insights'))
    )
    op.create_index('ix_insights_run_relevance', 'insights', ['run_uuid', 'relevance_score'], unique=False, postgresql_ops={'relevance_score': 'DESC'})
    op.create_table('recommendations',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('run_uuid', sa.Uuid(), nullable=False),
    sa.Column('target_query_uuid', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.Enum('blog_post', 'landing_page', 'faq', 'comparison', 'case_study', name='content_type'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('target_keywords', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='priority'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['pipeline_runs.uuid'], name=op.f('fk_recommendations_run_uuid_pipeline_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_query_uuid'], ['discovered_queries.uuid'], name=op.f('fk_recommendations_target_query_uuid_discovered_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_recommendations'))
    )
    op.create_index('ix_recommendations_run_priority', 'recommendations', ['run_uuid', 'priority'], unique=False)
    op.create_index(op.f('ix_recommendations_target_query_uuid'), 'recommendations', ['target_query_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_target_query_uuid'), table_name='recommendations')
    op.drop_index('ix_recommendations_run_priority', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_insights_run_relevance', table_name='insights', postgresql_ops={'relevance_score': 'DESC'})
    op.drop_table('insights')
    op.drop_index('ix_discovered_queries_run_status', table_name='discovered_queries')
    op.drop_index('ix_discovered_queries_run_opportunity', table_name='discovered_queries', postgresql_ops={'opportunity_score': 'DESC'})
    op.drop_index('ix_discovered_queries_profile_discovered', table_name='discovered_queries')
    op.drop_table('discovered_queries')
    op.drop_index(op.f('ix_pipeline_runs_profile_uuid'), table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_profile_started', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_correlation_id', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_profiles_domain'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###

    # Autogenerate creates native enum types alongside the tables that use them, but does not
    # drop them: the generated downgrade above leaves all five behind, so a subsequent upgrade
    # fails on "type already exists". Dropping them explicitly is what makes this migration
    # genuinely reversible - which is what a rolled-back deploy depends on.
    for enum_name in (
        "priority",
        "content_type",
        "visibility_status",
        "degradation_reason",
        "run_status",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
